#!env/bin/python


import argparse
import datetime
import logging
import os
import time
from configparser import ConfigParser
from pathlib import Path
from string import Template

import coloredlogs
import psycopg2
import sentry_sdk
from dotenv import load_dotenv

TEMPLATE_PATH = Path(__file__).parent.resolve().joinpath("cgit-template.txt")
ENTRY_TEMPLATE = Template(TEMPLATE_PATH.read_text())


def get_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("gitea_config", type=argparse.FileType("r"))
    parser.add_argument("output_file", type=argparse.FileType("w"))
    return parser.parse_args()


def read_gitea_config(gitea_config_file):
    config = ConfigParser()
    config.read_string("[root]\n" + gitea_config_file.read())
    return config


def get_database_credentials(gitea_config):
    database_config = gitea_config["database"]
    return {
        "dbname": database_config["name"],
        "user": database_config["user"],
        "password": database_config["passwd"],
    }


def get_db_connection(db_credentials):
    return psycopg2.connect(**db_credentials)


def get_owners(db_conn):
    with db_conn.cursor() as cursor:
        cursor.execute('SELECT id, lower_name FROM "user";')
        return dict(cursor.fetchall())


def get_repos(db_conn):
    with db_conn.cursor() as cursor:
        cursor.execute(
            "SELECT lower_name, description, website, owner_id from repository where is_private = false;"
        )
        return cursor.fetchall()


def main(gitea_config, output_file):
    repo_root = gitea_config["repository"]["ROOT"]
    with get_db_connection(get_database_credentials(gitea_config)) as db_conn:
        owners = get_owners(db_conn)
        logging.info("Got %s owners", len(owners))
        repos = get_repos(db_conn)
        logging.info("Got %s repos", len(repos))
    args.output_file.write(
        "# Generated by gitea-cgit-adapter on " + datetime.datetime.now().isoformat()
    )
    for name, description, website, owner_id in repos:
        owner_name = owners[owner_id]
        repo_ident = os.path.join(owner_name, name)
        logging.debug("Exporting %s", repo_ident)
        path = os.path.join(repo_root, repo_ident + ".git")
        assert os.path.exists(path)
        output_file.write(
            ENTRY_TEMPLATE.substitute(
                name=name,
                path=path,
                desc=description,
                owner=owner_name,
                website=website,
            )
        )


if __name__ == "__main__":
    coloredlogs.install(
        level=logging.INFO,
        fmt="%(asctime)s %(levelname)s %(message)s",
        datefmt="%H:%M:%S",
    )
    load_dotenv()
    sentry_sdk.init(os.environ.get("SENTRY_SDK"))
    args = get_args()
    gitea_config = read_gitea_config(args.gitea_config)
    main(gitea_config, args.output_file)
    if args.interval:
        while True:
            args.output_file.flush()
            args.output_file.seek(0)

            time.sleep(args.interval)

            gitea_config = read_gitea_config(args.gitea_config)
            main(gitea_config, args.output_file)
