name: Main

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dev dependencies
      run: pip install -r dev-requirements.txt
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run tests
      run: ./scripts/test.sh
    - name: Build docker image
      run: docker build .
